process.env.SANA_DATA_DIR = process.env.TMP_DIR!;
const { SanaStore } = await import("../src/store/db.js");
const now = Date.now();
const st = new SanaStore();
const seg = (t:string)=>JSON.stringify([{speaker:"A",words:t.split(" ").map((w,i)=>({text:w,start_timestamp:i,end_timestamp:i+1}))}]);
st.upsertMeeting({id:"m1",name:"Budget review, final round",source:"sana-ai:meeting",created_at_ms:now});
st.saveTranscript({meeting_id:"m1",text:"we should adjust the pricing on products now",json:seg("we should adjust the pricing on products now"),word_count:8,segment_count:1});
st.updateSyncState({ phase:"synced", blocking:0, last_full_sync_ms:now, meetings_total:1, transcripts_total:1, transcripts_done:1, daemon_pid:1, daemon_heartbeat_ms:now });
st.close();
const { sana } = await import("../src/tools/dispatch.js");
console.log(await sana("search",{query:"pricing"}));
process.exit(0);
