process.env.SANA_DATA_DIR = process.env.TMP_DIR!;
const { SanaStore } = await import("../src/store/db.js");
const now = Date.now();
const st = new SanaStore();
const mk=(id,name,off,lines)=>{ st.upsertMeeting({id,name,source:"sana-ai:meeting",created_at_ms:now-off,processing_phase:"done"});
  const segs=lines.map((t,i)=>({speaker:"S",words:t.split(" ").map((w,j)=>({text:w,start_timestamp:i*10+j,end_timestamp:i*10+j+1}))}));
  st.saveTranscript({meeting_id:id,text:lines.join("\n"),json:JSON.stringify(segs),word_count:100,segment_count:lines.length}); };
mk("mA","Pricing meeting",0,["we should adjust the pricing strategy","the pricing model needs pricing review pricing","unrelated chatter about lunch"]);
mk("mB","Category talk",86400000,["this is about categories and categorization","no relevant term here"]);
st.updateSyncState({phase:"synced",blocking:0,last_full_sync_ms:now,daemon_pid:1,daemon_heartbeat_ms:now});
st.close();
const { sana } = await import("../src/tools/dispatch.js");
console.log("=== search 'pricing' (best/BM25) ===\n"+await sana("search",{query:"pricing"}));
console.log("\n=== search 'cat' (word-boundary: should NOT match 'category') ===\n"+await sana("search",{query:"cat"}));
console.log("\n=== search 'adjust pricing' (both terms) ===\n"+await sana("search",{query:"adjust pricing"}));
process.exit(0);
